// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp  (
  options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetka-e3bXgN6--m9PMAzw6gFS7oyGGnU',
    appId: '1:721037065826:web:2b76561241ca6458929b3b',
    messagingSenderId: '721037065826',
    projectId: 'soda-happily-practice',
    authDomain: 'soda-happily-practice.firebaseapp.com',
    storageBucket: 'soda-happily-practice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-2FXAVfNClkfuWbT_nvZdEAyFS3GCjE',
    appId: '1:721037065826:android:cfd7a547a34306ab929b3b',
    messagingSenderId: '721037065826',
    projectId: 'soda-happily-practice',
    storageBucket: 'soda-happily-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiCke4QTWRqbffl8L4qDNPmvoRO4B1F6U',
    appId: '1:721037065826:ios:b4320c34600c9cbf929b3b',
    messagingSenderId: '721037065826',
    projectId: 'soda-happily-practice',
    storageBucket: 'soda-happily-practice.firebasestorage.app',
    iosBundleId: 'com.example.ver1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiCke4QTWRqbffl8L4qDNPmvoRO4B1F6U',
    appId: '1:721037065826:ios:b4320c34600c9cbf929b3b',
    messagingSenderId: '721037065826',
    projectId: 'soda-happily-practice',
    storageBucket: 'soda-happily-practice.firebasestorage.app',
    iosBundleId: 'com.example.ver1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAetka-e3bXgN6--m9PMAzw6gFS7oyGGnU',
    appId: '1:721037065826:web:7f8517cf2ac809cd929b3b',
    messagingSenderId: '721037065826',
    projectId: 'soda-happily-practice',
    authDomain: 'soda-happily-practice.firebaseapp.com',
    storageBucket: 'soda-happily-practice.firebasestorage.app',
  );
}
