// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUsgHocWX3Uy-alTy_eUfVC9neWGT0284',
    appId: '1:320869289971:web:705dd9e9c483b3d5b8cc86',
    messagingSenderId: '320869289971',
    projectId: 'happily-2d562',
    authDomain: 'happily-2d562.firebaseapp.com',
    storageBucket: 'happily-2d562.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4hv0UWPUzJyRsQd0yQbg5fO3XheswOpA',
    appId: '1:320869289971:android:8c22588d52ebdab8b8cc86',
    messagingSenderId: '320869289971',
    projectId: 'happily-2d562',
    storageBucket: 'happily-2d562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5N5mYjq5JGY5w8kKqU6kqYNKJJtW2SbA',
    appId: '1:320869289971:ios:d3337d34183187cfb8cc86',
    messagingSenderId: '320869289971',
    projectId: 'happily-2d562',
    storageBucket: 'happily-2d562.firebasestorage.app',
    iosBundleId: 'com.example.ver1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5N5mYjq5JGY5w8kKqU6kqYNKJJtW2SbA',
    appId: '1:320869289971:ios:d3337d34183187cfb8cc86',
    messagingSenderId: '320869289971',
    projectId: 'happily-2d562',
    storageBucket: 'happily-2d562.firebasestorage.app',
    iosBundleId: 'com.example.ver1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUsgHocWX3Uy-alTy_eUfVC9neWGT0284',
    appId: '1:320869289971:web:d2cce218000e67dab8cc86',
    messagingSenderId: '320869289971',
    projectId: 'happily-2d562',
    authDomain: 'happily-2d562.firebaseapp.com',
    storageBucket: 'happily-2d562.firebasestorage.app',
  );
}
